### PR TITLE
fix: missing env var INFLUXDB_URL

### PR DESCRIPTION
**Pull request by ackintosh**
This PR fixes https://github.com/testground/testground/issues/1428. 

> MESSAGE << sidecar >> InfluxDB unavailable; no metrics will be dispatched: no InfluxDB URL in $INFLUXDB_URL env var

### CODE REVIEW

**Comment by laurentsenta** [comment]
@ackintosh thanks for sharing! Could you rebase on the latest master? I'll trigger another CI run and make sure we review this soon.

**Comment by ackintosh** [comment]
I have rebased this on the latest master branch. 😃

**Comment by Arqu** [comment]
FWIW I'd love to get this fixed, but with the patch applied locally I still keep getting that warning / no metrics exported.
I might be holding it wrong though :/

**Comment by b5** [comment]
can we merge this please? Move the bytes working group is already relying on this patch

**Review by nonsense — APPROVED** [review]

**Review by laurentsenta — APPROVED** [review]
lgtm, thanks for sharing this fix, I'll merge today.

**Comment by laurentsenta** [comment]
Merged, thanks for the fix @ackintosh ! And thanks for the heads up @b5 , @Arqu

**Pull request merged**
