### PR TITLE
Basic TCP client/server upload test plan

### PR DESCRIPTION
**Pull request by jimpick**
This branch depends on the sidecar changes in PR #271 

Here is what it does:

This test plan constructs a very simple TCP client/server setup using only go standard library networking, where a single server accepts uploads from one or more clients. It is intended for providing a very simple baseline test to test connectivity within the testground networking environment.

It is a very simple test plan with very few dependencies, so it could potentially function as an introduction for writing testground test plans.

Currently, there is a test case `basic-tcp/upload` which simply streams data from a client to a server.

```
$ ./testground run basic-tcp/upload
found cached docker image for: testground-basic-tcp:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   0.0000s    MESSAGE << db8e8020e895 >> Sender: 8.0.0.2
   0.0000s    MESSAGE << d08d869a7c34 >> Receiver: 8.0.0.3
   0.2450s     METRIC << db8e8020e895 >> {"name":"sent_bytes","unit":"bytes","improve_dir":-1,"value":1024000}
   0.2450s     METRIC << db8e8020e895 >> {"name":"time_to_send","unit":"ms","improve_dir":-1,"value":0}
   0.2451s         OK << db8e8020e895 >> 
   0.2451s     METRIC << d08d869a7c34 >> {"name":"received_bytes","unit":"bytes","improve_dir":-1,"value":1024000}
   0.2451s     METRIC << d08d869a7c34 >> {"name":"time_to_receive","unit":"ms","improve_dir":-1,"value":0}
   0.2452s         OK << d08d869a7c34 >> 
```

There is also a test case `basic-tcp/upload-with-shaping` which does the same thing, but using the sidecar to do traffic shaping. Currently, this test case appears to be unreliable and stalls often -- I am planning to investigate further in case it is an issue with sidecar (it might just be a coding mistake on my side).

Tasks:

- [ ] Write a README.md
- [x] Investigate stalls with `basic-tcp/upload-with-shaping` test case
- [x] Parameterize number of bytes to send, bytes per write, and read buffer size
- [x] Parameterize throttling parameters
- [x] Test with more than one client
- [ ] Get more feedback
- [x] Rebase to master after PR #271 is merged

Future work:

* Add download tests

### CODE REVIEW

**Comment by jimpick** [comment]
An idea for a future test case ... a bi-directional upload/download test. This might be useful for verifying connection on overlay networks - eg. spin up 100 containers, and generate a grid to verify that every container can talk to every other container. For large number of containers, it would be good to have the ability to control the parallelism.

**Comment by jimpick** [comment]
The `basic-tcp/upload-with-shaping` test case is working now. I was shutting down my client container that was performing the throttled upload too early -- I needed to wait until the data was received before ending the test.

Needs #286 to set the REDIS_HOST environment variable on the sidecar when running via local:docker

```
$ ./testground run basic-tcp/upload-with-shaping
found cached docker image for: testground-basic-tcp:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   0.0000s    MESSAGE << 81f51d01903e >> Waiting for network to be initialized
   0.0000s    MESSAGE << 54ffb14e631f >> Waiting for network to be initialized
   0.2302s    MESSAGE << 54ffb14e631f >> Network initialized
   0.2475s    MESSAGE << 81f51d01903e >> Network initialized
   0.4839s    MESSAGE << 54ffb14e631f >> Network configured
   0.4851s    MESSAGE << 54ffb14e631f >> Receiver: 8.0.0.2
   0.5015s    MESSAGE << 81f51d01903e >> Network configured
   0.5033s    MESSAGE << 81f51d01903e >> Sender: 8.0.0.3
   7.3656s     METRIC << 81f51d01903e >> {"name":"sent_bytes","unit":"bytes","improve_dir":-1,"value":1024000}
   7.3657s     METRIC << 81f51d01903e >> {"name":"time_to_send","unit":"ms","improve_dir":-1,"value":6607}
   8.9028s     METRIC << 54ffb14e631f >> {"name":"received_bytes","unit":"bytes","improve_dir":-1,"value":1024000}
   8.9030s     METRIC << 54ffb14e631f >> {"name":"time_to_receive","unit":"ms","improve_dir":-1,"value":8144}
   8.9038s         OK << 54ffb14e631f >> 
   9.1188s         OK << 81f51d01903e >> 

```

**Comment by jimpick** [comment]
Demo as a GIF:

basic-tcp-upload

With Traffic Shaping, it takes 8.1s to receive the data.

**Comment by raulk** [comment]
@jimpick I'm closing this experimentation PR as it's been inactive for a while.

**Pull request closed without merging**
