### PR TITLE
draft: ci: add unified ci

### PR DESCRIPTION
**Pull request by laurentsenta**
- Tweak testground to make it work with unified ci,
- Add integration tests

## Tasks

- [x] go-test workflow
- [x] go-check workflow
- [x] add integration workflow
- [x] skip tests that depends on docker when running in macos and windows
- [x] disable broken tests on macos build (remove the plan folders)
- [ ] add ourselves to unified ci "officially"

### CODE REVIEW

**Comment by laurentsenta** [comment]
(TODO: split into 2 PRs, unified CI vs release)

**Comment by BigLep** [comment]
@laurentsenta : I see there are a lot of notes since the last commit.  What are the next steps for landing this?

**Comment by laurentsenta** [comment]
@BigLep, sorry for the latency; I've been focusing on other features on testground, and adding unified CI was pushed down our priority stack.

Ideally, we'll come back to it with https://github.com/testground/testground/issues/1430

**Comment by laurentsenta** [comment]
Closing this PR, we haven't got a chance to complete it.

@Bidon15 fyi, this is related to https://github.com/testground/testground/issues/1430; the PR was adding unified CI and updating the go version; that might be code you'd want to reuse later.

**Pull request closed without merging**
