### PR TITLE
fix: handle k8s .initPool error

### PR DESCRIPTION
**Pull request by hacdias**
Handle the return error of `initPool`, fixing #1239.

I did not manually test this PR. @nonsense @raulk can you build this branch and check if #1239 is fixed?

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by hacdias** [comment]
Interestingly, now the k8s tests fail saying they could not connect to Redis. I will investigate this further next week.

**Comment by hacdias** [comment]
Looking at the master branch, it seems that the sync client on k8s tests on CI is silently failing by just printing an error: https://app.circleci.com/pipelines/github/testground/testground/1028/workflows/387b2c31-18c6-4b22-9acb-c9a1cbf4166f/jobs/3582

That needs to be fixed on this PR in order for tests to pass.

**Comment by hacdias** [comment]
More insight into the error:

```
Jun 29 07:31:57.385269	INFO	performing healthcheck on runner
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x84f789]

goroutine 32 [running]:
github.com/testground/testground/pkg/api.(*HealthcheckReport).FixesSucceeded(0x0, 0x1f4fed0)
	/home/circleci/project/pkg/api/healthcheck.go:71 +0x29
github.com/testground/testground/pkg/engine.(*Engine).doRun(0xc000294000, 0x1f4fed0, 0xc0004ba060, 0xc0005f0300, 0x14, 0xc0003c55f0, 0xc0000fc420, 0xc0006339a0, 0x4, 0x4)
	/home/circleci/project/pkg/engine/supervisor.go:515 +0x15ec
github.com/testground/testground/pkg/engine.(*Engine).worker.func1(0xc000633cd8, 0xc000294000, 0xc0005e2c00, 0xc000633cf0, 0x1)
	/home/circleci/project/pkg/engine/supervisor.go:115 +0x15d7
github.com/testground/testground/pkg/engine.(*Engine).worker(0xc000294000, 0x1)
	/home/circleci/project/pkg/engine/supervisor.go:181 +0x2bc
created by github.com/testground/testground/pkg/engine.NewEngine
	/home/circleci/project/pkg/engine/engine.go:121 +0x61c
```

**Comment by hacdias** [comment]
merge #1250 first

**Comment by daonb** [comment]
Seems like #1250 its merged, looks like it's time to run build-test-linux again.

**Review by nonsense — APPROVED** [review]

**Pull request merged**
