### PR TITLE
Test plan for autonat correctness

### PR DESCRIPTION
**Pull request by willscott**
Adds a test with some connectable bootstrap nodes, and some natted nodes. confirms dialing connectivity, and that eventual autonat status of nodes is as expected.

### CODE REVIEW

**Comment by coryschwartz** [comment]
@raulk @nonsense looks okay to me, so long as the tests pass against master.

**Comment by willscott** [comment]
i'll expect to keep rebasing this forward until we've got released tags of autonat and libp2p it can run against rather than specific commits

**Comment by Robmat05** [comment]
@raulk this ticket hasn’t been selected for the v0.4 sprint. Is this a ticket we should add to this sprint for dev work?

**Comment by willscott** [comment]
> @raulk this ticket hasn’t been selected for the v0.4 sprint. Is this a ticket we should add to this sprint for dev work?

I don't think there is an ask from the testground team on time related to this task. This was a test plan i've been working on to validate functional correctness of the autonat subsystem within libp2p.

**Comment by Robmat05** [comment]
Thanks for clarifying @willscott , I’ll circle with my dev team and determine how we can support you best without impacting our dev sprint.

**Comment by raulk** [comment]
Hey @willscott; mind submitting this plan to https://github.com/libp2p/test-plans? All project-specific plans now live in external repos. Thanks!

**Pull request closed without merging**
